services:
  db:
    image: postgres:17
    container_name: sellercabinet-db 
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports: 
      - "5433:5432"
    volumes: 
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U seller_user -d sellercabinet"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  app: 
    build: . 
    container_name: sellercabinet-app
    depends_on:
      db: 
        condition: service_healthy
    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      JAVA_TOOL_OPTIONS: >-
        -Dfile.encoding=UTF-8
        -Dstdout.encoding=UTF-8
        -Dstderr.encoding=UTF-8
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/sellercabinet
      SPRING_DATASOURCE_USERNAME: seller_user
      SPRING_DATASOURCE_PASSWORD: seller_pass
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
    ports:
      - "8080:8080"
    restart: on-failure
    stdin_open: true
    tty: true

volumes:
  pgdata: