spring.application.name=sellercabinet

spring.datasource.url=jdbc:postgresql://localhost:5432/sellercabinet
spring.datasource.username=seller_user
spring.datasource.password=seller_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
